name: lenra_ui_runner
description: Implementation of the Lenra Component API in Dart with the Flutter framework.
version: 0.0.0
publish_to: none
environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  lenra_components:
    git:
      url: git@github.com:lenra-io/lenra_components.git
      ref: v1.0.0-beta.52
  client_common:
    git:
      url: git@github.com:lenra-io/client-common.git
      ref: v1.0.0-beta.38
  json_patch: ^3.0.0
  mockito: ^5.0.17
  phoenix_wings: ^1.0.2
dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
flutter:
  uses-material-design: true
