name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"
jobs:
  release:
    uses: ${{ env.WORKFLOW_PATH }}/release.yml@${{ env.WORKFLOW_REF }}
    secrets:
      token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
