name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"
jobs:
  release:
    uses: ${WORKFLOW_PATH}/release.yml@${WORKFLOW_REF}
    secrets:
      token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
