name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"
jobs:
  release:
    uses: lenra-io/github-actions/.github/workflows/release.yml@2-task-add-semantic-release
    secrets:
      token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}