name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"
jobs:
  release:
    uses: lenra-io/github-actions/.github/workflows/release.yml@c143fa6a470cd4da270356bfa073d3a89bbe6496
    secrets:
      token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
